env:
  browser: true
  es2021: true
extends:
  - xo
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: script
plugins:
  - import
rules:
  arrow-parens: 0
  comma-dangle: off
  object-curly-spacing: 0
  import/no-unresolved: [2]
