env:
  browser: true
  es2021: true
extends:
  - xo
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - import
  - redos
rules:
  arrow-parens: 0
  object-curly-spacing: 0
  import/no-unresolved: [2]
  redos/no-vulnerable: error
overrides:
- files:
  - "**/*.spec.js"
  rules:
    redos/no-vulnerable: 'off'
